<template>
  <div>
    <Header hide="true" icon1="/svg/profile-icon.svg" icon3="/svg/profile-icon.svg"  icon2="/svg/Notification.svg"/>
      <v-container style="width: 100%;">
          <v-row no-gutters style="margin-top: 90px;">
            <div style="display: flex;">
              <div cols="4">
                <div class="pa-2 ma-2">
                    <Side-nav/>
                </div>
              </div>

              <div cols="8" style="width: 74%">
                <div class="pa-2 ma-2">
                    
                    <div class="acct-settings" :class="isDark ? 'profile-cards-dark':'profile-cards-light'" style="display: flex; justify-content: space-between">    
                        <span class="acct-text"> Security</span>
                        <span class="mail-text" :class="isDark ? 'text-dark':'text-light'">{{ pinia.state.email }}</span>  
                    </div>
                    <span class="setup-text ml-2" :class="isDark ? 'card-text-dark':'card-text-light'">Setup your 2FA and make your account more secure</span>
                    <section>
                      
                        <div style="margin-top:35px !important; display:flex; justify-content: space-between;">
                            <div class="d-flex">
                                  <img src="/svg/lock-circle (1).svg" class="me-4" style="display: flex; align-self: start;"/>
                                <div style="display: grid;">
                                  <span class="pswrd-mgt" style="color: white;">Google Authenticator or Authy</span>
                                  <span class="second-text" :class="isDark ? 'text-dark':'text-light'" style="margin-top: 4px;">Random time-bound passcode generated by the app</span>
                                </div>
                            </div>

                            <v-btn :class="{'primarybtn': Authy === 'initial2', 'toggled': Authy === 'toggled'}"
                            @click="toggleState3" width="100px"> {{ Authy === 'initial2' ? 'Enable' : 'Disable' }}
                            </v-btn>
                          
                          
                        </div>
                        
                      <div style="margin-top: 42px;">
                          <span class="pswrd-mgt" :class="isDark ? 'card-text-dark':'card-text-light'" style="font-weight: 700;" @click="userPassword()">Change Password</span>
                          <div class="d-flex" style="align-items: center;">
                              <Password class=" me-4" placeholder="Enter current password"/>
                              <NuxtLink to="#"><span class="second-text" style="color: var(--Primary-100, #2873FF); padding-top: 25px;">Forgot password</span></NuxtLink>
                          </div>
                          <div class="d-flex">
                              <Password class="me-5" placeholder="Enter new password"/>  <Password class="me-7" placeholder="confirm new password"/>
                              <v-btn class="primarybtn mt-5" style=" align-self: center;">Change Password</v-btn>
                          </div>
                        <div  style="display: inline-flex;">
                            <v-checkbox base-color="#fff" color="white" ></v-checkbox>
                            <span style="align-self: flex-start; margin-top: 16px; font-weight: 400;color: var(--Gray-Light, #D8D8D8); font-family: Poppins; font-size: 14px;">Log out of all active sessions</span>
                        </div>
                      </div>
                    </section>
                  <Active-sessions/>
                </div>
              </div>     
            </div>
          </v-row>
      </v-container>   
          <Footer/>
  </div>
</template>
<script setup>
import { ref } from 'vue'
import { useTheme } from 'vuetify';
import { passwordUpdate } from "@/composables/requests/users";

const theme = useTheme()
const isDark = computed(() =>  theme.global.current.value.dark);
const pinia = useStore();
const login = ref('initial1'); // Initial state for button

const Authy = ref('toggled');
const toggleState3 = () => {
Authy.value = Authy.value === 'initial2' ? 'toggled' : 'initial2';
};

const userPassword = async () => {
  const updatePassword = {
    old_password: "",
    new_password: "",
  }
  
  try {
  const data = await userPassword(updatePassword);
  if (data.success) {
    console.log('password changed succesfully')
  } else{
    
    console.error('unauthorized user');
  }
}catch(e){
  console.log(e)
};
 
};
</script>
<style>

.mail-text{
font-family: Manrope;
font-size: 16px;
font-style: normal;
font-weight: 500;
line-height: 28px; 
}

.toggled {
border-radius: 16px;
background: #1C242E;
height: 60px !important;
text-transform: unset!important;
letter-spacing: 0px;
box-shadow: none;
}
.input-styling{
  width: 350px;
  height: 64px !important;
  background: var(--secondary-background, #12181F) !important;
  border-radius: 15px ;
}
.second-text{
font-family: Poppins;
font-size: 14px;
font-style: normal;
font-weight: 400;
line-height: normal;
}

.update-btn{
color: var(--Gray-Light, #D8D8D8);
font-family: Manrope;
font-size: 16px;
font-style: normal;
font-weight: 600;
line-height: normal;
display: flex;
width: 224px;
height: 64px!important;
padding: 21px 16px;
justify-content: center;
align-items: center;
gap: 8px;
border-radius: 16px;
background: var(--Primary-100, linear-gradient(180deg, #2873FF 0%, #0B6B96 100%), #2873FF);
text-transform: unset!important;
box-shadow: none !important;
}
.setup-text{
font-family: Poppins;
font-size: 16px;
font-style: normal;
font-weight: 700;
line-height: normal;
margin-top: 16px;
}
.pswrd-mgt{
font-family: Poppins;
font-size: 16px;
font-style: normal;
font-weight: 600;
line-height: normal;
}
.primarybtn{
/* width: 100px; */
height: 60px!important;
flex-shrink: 0;
border-radius: 16px;
background: var(--Primary-100, linear-gradient(180deg, #2873FF 0%, #0B6B96 100%), #2873FF)!important;
color: var(--White, var(--Colors-Base-white, #FFF));
text-align: center;
font-family: Poppins;
font-size: 14px;
font-style: normal;
font-weight: 400;
line-height: normal;
text-transform: unset !important;
letter-spacing: 0px;
box-shadow: none;
}
.mdi-checkbox-blank-outline::before {
    content: "\F0131" !important;
    background: white !important;
    border-radius: 8px !important;
    fill: white;
}

::-webkit-input-placeholder {
color: #808195!important;
font-size: 0.875rem !important;
font-style: normal;
font-size: 14px;
font-weight: 400;
line-height: normal;
display: flex !important;
width:190px !important;
}
.profile-cards-dark{
background:  #10192D!important;
box-shadow: rgba(0, 0, 0, 0.1) 0px 4px 12px !important;
height: fit-content;
}
.profile-cards-light{
background: #F8FAFC!important;
height: fit-content;

}
</style>