<template>
  <div>
          <v-row no-gutters style="overflow:;">
            <v-col cols="3">
              <div class="pa-2 ma-2">
                          <!-- //side nav here../ -->
              </div>
            </v-col>

            <v-col cols="9">
              <div class="pa-2 ma-2">
                  
                  <div class="acct-settings" style="display: flex; justify-content: space-between">    
                      <span class="acct-text"> Security</span>
                      <span class="mail-text">vaststudiosng@gmail.com</span>  
                  </div>
                  <span class="setup-text">Setup your 2FA and make your account more secure</span>
                  <div style="margin-top: 35px">
                    <span class="pswrd-mgt">Password Management</span>
                  </div>
                  <section style="width: 938px;">
                      <div style="margin-top:34px !important; display:flex; justify-content: space-between;">
                          <div class="d-flex">
                                <img src="/svg/Item.svg" class="me-4" style="display: flex; align-self: start;"/>
                              <div style="display: grid">
                                <span class="pswrd-mgt" style="white">Login 2-Step Verification</span>
                                <span class="second-text"> The Login 2step Verification adds an extra layer of security to your account.</span>
                              </div>
                          </div>
                            <v-btn class="primary-btn"  width="100px">Enable</v-btn>
                      </div>
                      <div style="margin-top:23px !important; display:flex; justify-content: space-between;">
                          <div class="d-flex">
                                <img src="/svg/sms (2).svg" class="me-4" style="display: flex; align-self: start;"/>
                              <div style="display: grid">
                                <span class="pswrd-mgt" style="white">Email Setup</span>
                                <span class="second-text" style="margin-top: 4px"> Please enter your email correctly</span>
                              </div>
                          </div>
                            <v-btn class="primary-btn" width="100px">Enable</v-btn>
                      </div>
                      <div style="margin-top:23px !important; display:flex; justify-content: space-between;">
                          <div class="d-flex">
                                <img src="/svg/lock-circle (1).svg" class="me-4" style="display: flex; align-self: start;"/>
                              <div style="display: grid">
                                <span class="pswrd-mgt" style="white">Google Authenticator or Authy</span>
                                <span class="second-text" style="margin-top: 4px"> Random time-bound passcode generated by the app</span>
                              </div>
                          </div>
                            <v-btn class="primary-btn"  width="100px" style="background: #1C242E !important;">Disable</v-btn>
                      </div>
                      <div style="margin-top:23px !important; display:flex; justify-content: space-between;">
                          <div class="d-flex">
                                <img src="/svg/circle-auth.svg" class="me-4" style="display: flex; align-self: start;"/>
                              <div style="display: grid">
                                <span class="pswrd-mgt" style="white">Security Questions</span>
                                <span class="second-text" style="margin-top: 4px"> Random time-bound passcode generated by the app</span>
                              </div>
                          </div>
                          <v-btn class="primary-btn"  width="100px">Enable</v-btn>
                      </div>
                    <div style="margin-top: 42px">
                        <span>Forgot Password</span>
                        <div class="d-flex">
                            <Password class=" me-4"/>
                            <span class="second-text mt-5" style="color: var(--Primary-100, #2873FF); align-self: center;">Forgot password</span>
                        </div>
                        <div class="d-flex">
                            <Password class="me-5"/>  <Password class="me-7"/>
                            <v-btn class="primary-btn mt-5" style=" align-self: center;">Change Password</v-btn>
                        </div>
                      <div  style="display: inline-flex;">
                          <v-checkbox color="primary"></v-checkbox>
                          <span style="align-self: flex-start; margin-top: 16px; font-weight: 400;color: var(--Gray-Light, #D8D8D8); font-family: Poppins; font-size: 14px;">Log out of all active sessions</span>
                      </div>
                    </div>
                  </section>
                <Active-sessions/>
              </div>

               

            </v-col>     
          </v-row>
          
          <Footer/>
  </div>
</template>
<script setup>
  import { ref } from 'vue'






</script>
<style >

.acct-settings{
border-radius: 16px;
background: var(--secondary-background, #12181F);
display: flex;
width: 940px;
padding: 21px var(--spacing-3xl, 24px);
justify-content: space-between;
align-items: center;
margin-bottom: 16px;
}
.acct-text{
color: var(--Primary-80, #5892FF);
font-family: Manrope;
font-size: 24px;
font-style: normal;
font-weight: 600;
line-height: 28px; 
}

.mail-text{
  color: var(--Gray-Medium-light, #969696);
font-family: Manrope;
font-size: 16px;
font-style: normal;
font-weight: 500;
line-height: 28px; 
}
.input-styling{
  width: 350px;
  height: 64px !important;
  background: var(--secondary-background, #12181F) !important;
  border-radius: 15px ;
}
.second-text{
color: var(--Second-Text, #A4A8AB);
font-family: Poppins;
font-size: 14px;
font-style: normal;
font-weight: 400;
line-height: normal;
}

.update-btn{
color: var(--Gray-Light, #D8D8D8);
font-family: Manrope;
font-size: 16px;
font-style: normal;
font-weight: 600;
line-height: normal;
display: flex;
width: 224px;
height: 64px!important;
padding: 21px 16px;
justify-content: center;
align-items: center;
gap: 8px;
border-radius: 16px;
background: var(--Primary-100, linear-gradient(180deg, #2873FF 0%, #0B6B96 100%), #2873FF);
text-transform: unset!important;
}
.setup-text{
color: var(--Colors-Base-white, #FFF);
font-family: Poppins;
font-size: 16px;
font-style: normal;
font-weight: 700;
line-height: normal;
margin-top: 16px;
}
.pswrd-mgt{
color: var( #A4A8AB);
font-family: Poppins;
font-size: 16px;
font-style: normal;
font-weight: 600;
line-height: normal;
}
.primary-btn{
/* width: 100px; */
height: 60px!important;
flex-shrink: 0;
border-radius: 16px;
background: var(--Primary-100, linear-gradient(180deg, #2873FF 0%, #0B6B96 100%), #2873FF)!important;
color: var(--White, var(--Colors-Base-white, #FFF));
text-align: center;
font-family: Poppins;
font-size: 14px;
font-style: normal;
font-weight: 400;
line-height: normal;
text-transform: unset !important;
letter-spacing: 0px;
}
.mdi-checkbox-blank-outline::before {
    content: "\F0131";
    background: white !important;
    border-radius: 8px;
}
</style>