<template>
  <div>
     <Header icon="/svg/white-wallet.svg" Menuicon="/svg/Main Menu Icons.svg" icon1="/svg/profile-icon.svg"  icon2="/svg/Notification.svg"/>
          <v-row no-gutters style="margin-top: 90px;">
            <v-col cols="3">
              <div class="pa-2 ma-2">
                          <!-- //side nav here../ -->
              </div>
            </v-col>

            <v-col cols="9">
              <div class="pa-2 ma-2">
                  
                  <div class="acct-settings" style="display: flex; justify-content: space-between">    
                      <span class="acct-text"> Security</span>
                      <span class="mail-text">vaststudiosng@gmail.com</span>  
                  </div>
                  <span class="setup-text">Setup your 2FA and make your account more secure</span>
                  <div style="margin-top: 35px">
                    <span class="pswrd-mgt">Password Management</span>
                  </div>
                  <section style="width: 938px;">
                      <div style="margin-top:34px !important; display:flex; justify-content: space-between;">
                          <div class="d-flex">
                                <img src="/svg/Item.svg" class="me-4" style="display: flex; align-self: start;"/>
                              <div style="display: grid">
                                <span class="pswrd-mgt" style="white">Login 2-Step Verification</span>
                                <span class="second-text"> The Login 2step Verification adds an extra layer of security to your account.</span>
                              </div>
                          </div>

                          <v-btn :class="{ 'toggled': login === 'toggled', 'primarybtn': login === 'initial1' }"
                           @click="toggleState1" width="100px"> {{ login === 'initial1' ? 'Enable' : 'Disable' }}
                          </v-btn>

                      </div>
                      <div style="margin-top: 23px !important; display: flex; justify-content: space-between;">
                          <div class="d-flex">
                                <img src="/svg/sms (2).svg" class="me-4" alt="SMS Icon" style="display: flex; align-self: start;"/>
                              <div style="display: grid;">
                                <span class="pswrd-mgt">Email Setup</span>
                                <span class="second-text" style="margin-top: 4px"> Please enter your email correctly</span>
                              </div>
                          </div>

                          <v-btn :class="{ 'toggled': Setup === 'toggled', 'primarybtn': Setup === 'initial1' }"
                           @click="toggleState2" width="100px"> {{ Setup === 'initial1' ? 'Enable' : 'Disable' }}
                          </v-btn>


                      </div>
                      <div style="margin-top:23px !important; display:flex; justify-content: space-between;">
                          <div class="d-flex">
                                <img src="/svg/lock-circle (1).svg" class="me-4" style="display: flex; align-self: start;"/>
                              <div style="display: grid;">
                                <span class="pswrd-mgt" style="color: white;">Google Authenticator or Authy</span>
                                <span class="second-text" style="margin-top: 4px;">Random time-bound passcode generated by the app</span>
                              </div>
                          </div>

                          <v-btn :class="{'primarybtn': Authy === 'initial2', 'toggled': Authy === 'toggled'}"
                           @click="toggleState3" width="100px"> {{ Authy === 'initial2' ? 'Enable' : 'Disable' }}
                          </v-btn>
                        
                         
                      </div>
                      <div style="margin-top:23px !important; display:flex; justify-content: space-between;">
                          <div class="d-flex">
                                <img src="/svg/circle-auth.svg" class="me-4" style="display: flex; align-self: start;"/>
                              <div style="display: grid">
                                <span class="pswrd-mgt" style="white">Security Questions</span>
                                <span class="second-text" style="margin-top: 4px"> Random time-bound passcode generated by the app</span>
                              </div>
                          </div>

                          
                          <v-btn :class="{ 'toggled': state === 'toggled', 'primarybtn': state === 'initial' }"
                           @click="toggleState" width="100px"> {{ state === 'initial' ? 'Enable' : 'Disable' }}
                          </v-btn>
                      
                        </div>
                    <div style="margin-top: 42px">
                        <span>Forgot Password</span>
                        <div class="d-flex" style="align-items: center;">
                            <Password class=" me-4" placeholder="Enter current password"/>
                            <NuxtLink to="#"><span class="second-text" style="color: var(--Primary-100, #2873FF); padding-top: 19px;">Forgot password</span></NuxtLink>
                        </div>
                        <div class="d-flex">
                            <Password class="me-5" placeholder="Enter new password"/>  <Password class="me-7" placeholder="confirm new password"/>
                            <v-btn class="primarybtn mt-5" style=" align-self: center;">Change Password</v-btn>
                        </div>
                      <div  style="display: inline-flex;">
                          <v-checkbox color="primary"></v-checkbox>
                          <span style="align-self: flex-start; margin-top: 16px; font-weight: 400;color: var(--Gray-Light, #D8D8D8); font-family: Poppins; font-size: 14px;">Log out of all active sessions</span>
                      </div>
                    </div>
                  </section>
                <Active-sessions/>
              </div>

               

            </v-col>     
          </v-row>
          
          <Footer/>
  </div>
</template>
<script setup>
import { ref } from 'vue'


const login = ref('initial1'); // Initial state for button

const toggleState1 = () => {
login.value = login.value === 'initial1' ? 'toggled' : 'initial1';
};

const Setup = ref('initial1');
const toggleState2 = () => {
Setup.value = Setup.value === 'initial1' ? 'toggled' : 'initial1';

};

const Authy = ref('toggled');
const toggleState3 = () => {
Authy.value = Authy.value === 'initial2' ? 'toggled' : 'initial2';
};

const state = ref('initial'); 

const toggleState = () => {
  state.value = state.value === 'initial' ? 'toggled' : 'initial';
};




</script>
<style >

.mail-text{
  color: var(--Gray-Medium-light, #969696);
font-family: Manrope;
font-size: 16px;
font-style: normal;
font-weight: 500;
line-height: 28px; 
}

.toggled {
border-radius: 16px;
background: #1C242E;
height: 60px !important;
text-transform: unset!important;
letter-spacing: 0px;
}
.input-styling{
  width: 350px;
  height: 64px !important;
  background: var(--secondary-background, #12181F) !important;
  border-radius: 15px ;
}
.second-text{
color: var(--Second-Text, #A4A8AB);
font-family: Poppins;
font-size: 14px;
font-style: normal;
font-weight: 400;
line-height: normal;
}

.update-btn{
color: var(--Gray-Light, #D8D8D8);
font-family: Manrope;
font-size: 16px;
font-style: normal;
font-weight: 600;
line-height: normal;
display: flex;
width: 224px;
height: 64px!important;
padding: 21px 16px;
justify-content: center;
align-items: center;
gap: 8px;
border-radius: 16px;
background: var(--Primary-100, linear-gradient(180deg, #2873FF 0%, #0B6B96 100%), #2873FF);
text-transform: unset!important;
}
.setup-text{
color: var(--Colors-Base-white, #FFF);
font-family: Poppins;
font-size: 16px;
font-style: normal;
font-weight: 700;
line-height: normal;
margin-top: 16px;
}
.pswrd-mgt{
color: var( #A4A8AB);
font-family: Poppins;
font-size: 16px;
font-style: normal;
font-weight: 600;
line-height: normal;
}
.primarybtn{
/* width: 100px; */
height: 60px!important;
flex-shrink: 0;
border-radius: 16px;
background: var(--Primary-100, linear-gradient(180deg, #2873FF 0%, #0B6B96 100%), #2873FF)!important;
color: var(--White, var(--Colors-Base-white, #FFF));
text-align: center;
font-family: Poppins;
font-size: 14px;
font-style: normal;
font-weight: 400;
line-height: normal;
text-transform: unset !important;
letter-spacing: 0px;
}
.mdi-checkbox-blank-outline::before {
    content: "\F0131";
    background: white !important;
    border-radius: 8px;
}
</style>